#user:
##  id: 17
##  f_name: 钱多多
##  stu: false
##  birth: 1999/09/01
##  sex: 男
##  maps: {k1: v1,k2: v2}
##  lists:
##  - 小红
##  - 小黄
##  - 小蓝
##  cat:
##    c_name: 大橘为重
##    color: 橘色

# thymeleaf
#  spring.thymeleaf.prefix=classpath:/templates/
#  spring.thymeleaf.check-template-location=true
#  spring.thymeleaf.suffix=.html
#  spring.thymeleaf.encoding=UTF-8
#  spring.thymeleaf.content-type=text/html
#  spring.thymeleaf.mode=HTML5
#  spring.thymeleaf.cache=false

spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8

    servlet:
      content-type: text/html
    mode: HTML5
    cache: false

  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/itjob?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath: jdbc15.sql
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  port: 8080

  mybatis:
    typeAliasesPackage: net.togogo.bean
    mapperLocations: classpath:mapper/*.xml
